#!/bin/bash
echo "usage: divutil (variable) (line number) (char num of the first char in second line)
echo -e "$1" | grep -n . | grep ^$2 | cut -d: -f2- | grep -no . | cut -d: -f2- | cut -d"
" -f-$(($3-1)) | cut -d: -f2- | tr -d \\n
echo -e ""
echo -e "$1" | grep -n . | grep ^$2 | cut -d: -f2- | grep -no . | cut -d: -f2- | cut -d"
" -f$3- | cut -d: -f2- | tr -d \\n
