#!/bin/bash
echo -e "$1" | grep -n . | grep ^$2: | cut -d: -f2- | tr \ , \\n | 
echo "enter word num"
read wd
o1=$(echo -e "$1" | grep -n . | grep ^$2: | cut -d: -f2- | cut -d \  -f-$(($wd-1)))
o2=$(echo -e "$1" | grep -n . | grep ^$2: | cut -d: -f2- | cut -d \  -f$(($wd+1))-)
echo -e "$o1$3$o2"
